name = str(input("Enter Employees' name: " ))
salary = int(input("Enter Employees' salary: "))
city = str(input ("Enter Employees' City: "))
isActive = bool(input ("Is the Employee active?: "))
efficiencyRate = float(input ("Enter Employees' efficiency rate: "))
print (type(name))
print (type(salary))
print (type(city))
print (type(isActive))
print (type(efficiencyRate))